In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import datetime as dt
%matplotlib inline
os.getcwd()

'C:\\Users\\metas\\Desktop\\@METAS\\1. Data_Analysis\\pandas_test'

In [2]:
print(dir(pd),end="\n\n")

print("List directory = " , os.listdir())

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

List directory =  ['.ipynb_checkpoints', '170Oven.xlsm', 'Pandas_for_data.ipynb', '~$170Oven.xlsm']

In [3]:
name = input("Input Yield/Table name(.xlsx or .xlsm) : ")
yield170 = pd.read_excel(name)
yield170.head()

Input Yield/Table name(.xlsx or .xlsm) : 170Oven.xlsm

,Lot No.,Item,Model,Freq,Op,Release Date,Input,Multiply,Output,Out Date,...,Board No. 24,จำนวนงานNGก่อนStart,VACUUM ERROR NG,MACHINE ID,Panel set M/C ID (Supply),Panel set M/C ID (Remove),End User ID,End User Name,ADJUST NG170,Rate ADJUST NG170
0,DHT1329600,SM27C034,TG-5501CA-34A 10.000000 MHz,10 MHz,170,2019-01-22,632,1,514,2019-01-16,...,0,0.0,0.0,0,0,0,60151,Wongduen Lapee,21.0,3.32
1,DHT1329900,SM27C034,TG-5501CA-34A 10.000000 MHz,10 MHz,170,2019-01-22,633,1,544,2019-01-16,...,0,0.0,0.0,0,0,0,20813,Banchong Aiabhuai,18.0,2.84
2,DHT1329400,SM27C034,TG-5501CA-34A 10.000000 MHz,10 MHz,170,2019-01-22,635,1,552,2019-01-16,...,0,0.0,0.0,0,0,0,60151,Wongduen Lapee,14.0,2.20
3,DHT1329700,SM27C034,TG-5501CA-34A 10.000000 MHz,10 MHz,170,2019-01-22,637,1,529,2019-01-17,...,0,0.0,0.0,0,0,0,20813,BANCHONG AIABHUAI,25.0,3.92
4,DHT1330200,SM27C034,TG-5501CA-34A 10.000000 MHz,10 MHz,170,2019-01-22,633,1,533,2019-01-17,...,0,0.0,0.0,0,0,0,140610,Orrapan Hanjan,40.0,6.32

In [4]:
print("shape = ",end='')
print(yield170.shape,sep = None,end='\n\n')
yield170.info()

shape = (1350, 67)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 67 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Lot No.                    1350 non-null   object
 1   Item                       1350 non-null   object
 2   Model                      1350 non-null   object
 3   Freq                       1350 non-null   object
 4   Op                         1350 non-null   int64
 5   Release Date               1350 non-null   datetime64[ns]
 6   Input                      1350 non-null   int64
 7   Multiply                   1350 non-null   int64
 8   Output                     1350 non-null   int64
 9   Out Date                   1350 non-null   datetime64[ns]
 10  Yield                      1350 non-null   float64
 11  Eng_Eval_NG                1350 non-null   int64
 12  Not Include Eng_Eval_NG    1350 non-null   int64
 13  All_Ng_Qty                 1350 non-null   int64
 14  All PPM                    1350 non-null   float64
 15  CAL PPM                    1350 non-null   float64
 16  ReceiveDate                1350 non-null   datetime64[ns]
 17  ReceiveTime                1350 non-null   object
 18  ActInDate                  1350 non-null   datetime64[ns]
 19  ActInTime                  1350 non-null   object
 20  ActOutDate                 1350 non-null   datetime64[ns]
 21  ActOuttime                 1350 non-null   object
 22  WaitStart(Minute)          1350 non-null   float64
 23  WaitStart(Hour)            1350 non-null   float64
 24  LeadTime(Minute)           1350 non-null   float64
 25  LeadTime(Hour)             1350 non-null   float64
 26  TCI                        1350 non-null   object
 27  Magazine No.1              1321 non-null   float64
 28  Average                    1321 non-null   float64
 29  Sigma                      1321 non-null   float64
 30  TCI Probe life time        1321 non-null   float64
 31  IBF TG                     1321 non-null   float64
 32  Software V.                1350 non-null   object
 33  Software SBOX V.           1349 non-null   object
 34  Board No. 1                1350 non-null   object
 35  Board No. 2                1350 non-null   object
 36  Board No. 3                1350 non-null   object
 37  Board No. 4                1350 non-null   object
 38  Board No. 5                1350 non-null   object
 39  Board No. 6                1350 non-null   object
 40  Board No. 7                1350 non-null   object
 41  Board No. 8                1350 non-null   object
 42  Board No. 9                1350 non-null   object
 43  Board No. 10               1350 non-null   object
 44  Board No. 11               1350 non-null   object
 45  Board No. 12               1350 non-null   object
 46  Board No. 13               1350 non-null   object
 47  Board No. 14               1350 non-null   object
 48  Board No. 15               1350 non-null   object
 49  Board No. 16               1350 non-null   object
 50  Board No. 17               1321 non-null   object
 51  Board No. 18               1320 non-null   object
 52  Board No. 19               1320 non-null   object
 53  Board No. 20               1320 non-null   object
 54  Board No. 21               1320 non-null   object
 55  Board No. 22               1320 non-null   object
 56  Board No. 23               1320 non-null   object
 57  Board No. 24               1320 non-null   object
 58  จำนวนงานNGก่อนStart        1320 non-null   float64
 59  VACUUM ERROR NG            1320 non-null   float64
 60  MACHINE ID                 1320 non-null   object
 61  Panel set M/C ID (Supply)  1320 non-null   object
 62  Panel set M/C ID (Remove)  1320 non-null   object
 63  End User ID                1320 non-null   object
 64  End User Name              1320 non-null   object
 65  ADJUST NG170               1320 non-null   float64
 66  Rate ADJUST NG170          1320 non-null   float64
dtypes: datetime64[ns](5), float64(16), int64(7), object(39)
memory usage: 706.8+ KB

In [5]:
lot170 = []
yieldTCI = []
out_date = []
mcid = []
rate_adj = []

for lot in yield170['Lot No.']:
    lot170.append(lot)
for y in yield170['Yield']:
    yieldTCI.append(y)
for d in yield170['Out Date']:
    out_date.append(d)
for ID in yield170['TCI'] : 
    mcid.append(str(ID))
for adj in yield170['Rate ADJUST NG170'] : 
    rate_adj.append(adj)

#Create DataFrame as date we use
df = pd.DataFrame(list(zip(yieldTCI,out_date,mcid,rate_adj)), index = lot170 , columns = ['yield','Date','M/C ID','ADJUST NG'])
df.sort_values('Date')
df['M/C ID'] = df['M/C ID'].str[-2:]
df['ADJUST NG'] = df['ADJUST NG'].fillna(value=0)
df

                yield       Date M/C ID  ADJUST NG
DHT1329600  81.329114 2019-01-16     10       3.32
DHT1329900  85.939968 2019-01-16     07       2.84
DHT1329400  86.929134 2019-01-16     03       2.20
DHT1329700  83.045526 2019-01-17     03       3.92
DHT1330200  84.202212 2019-01-17     03       6.32
...               ...        ...    ...        ...
DHY0990600  89.573460 2019-10-27     10       0.00
DHY0991900  91.324921 2019-10-27     06       0.00
DHY0991700  92.913386 2019-10-31     07       0.00
DHY0991600  92.924528 2019-11-01     07       0.00
DHY0991500  93.375394 2019-11-01     03       0.00

[1350 rows x 4 columns]